import type {Metadata} from "next";
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className='antialiased p-4'
      >
        This is <code>layout.tsx</code>
        {children}
      </body>
    </html>
  );
}
